
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class Blog
{

    public int BlogId { get; set; }

    public string BlogTitle { get; set; }

    public System.DateTime BlogDate { get; set; }

    public string BlogAuthor { get; set; }

    public string BlogCatergory { get; set; }

    public string BlogShort { get; set; }

    public string BlogBody { get; set; }

    public string BlogImg { get; set; }

    public int BlogView { get; set; }

}

}
