
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class Committee
{

    public int CommitteeId { get; set; }

    public string CommitteeName { get; set; }

    public string CommitteePosition { get; set; }

    public string CommitteeImg { get; set; }

    public string CommitteeDetails { get; set; }

    public int CommitteeYear { get; set; }

    public int CommitteeSemester { get; set; }

    public string CommitteeFacebook { get; set; }

    public string CommitteeEmail { get; set; }

    public int CommitteeStatus { get; set; }

    public string CommitteeIteration { get; set; }

}

}
