
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class Contest
{

    public int ContestId { get; set; }

    public string ContestTitle { get; set; }

    public string ContestDesc { get; set; }

    public string ContestImg { get; set; }

    public System.DateTime ContestStart { get; set; }

    public System.DateTime ContestEnd { get; set; }

}

}
