
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class CssVariables1
{

    public int VarId { get; set; }

    public string VarName { get; set; }

    public string VarValue { get; set; }

}

}
