
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class Gallery
{

    public int ImgId { get; set; }

    public string ImgTitle { get; set; }

    public string ImgDesc { get; set; }

    public string ImgUrl { get; set; }

}

}
