
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    public int MemberId { get; set; }

    public string MemberName { get; set; }

    public int MemberAustId { get; set; }

    public string MemberDept { get; set; }

    public int MemberYear { get; set; }

    public int MemberSemester { get; set; }

    public string MemberEmail { get; set; }

    public int MemberMobile { get; set; }

    public System.DateTime MemberBirth { get; set; }

    public string MemberBloodgrp { get; set; }

    public System.DateTime MemberJoined { get; set; }

}

}
