

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AustPIC.db
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AustPICEntities : DbContext
{
    public AustPICEntities()
        : base("name=AustPICEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Gallery> Gallery { get; set; }

    public virtual DbSet<Member> Member { get; set; }

    public virtual DbSet<Contact> Contact { get; set; }

    public virtual DbSet<Committee> Committee { get; set; }

    public virtual DbSet<Blog> Blog { get; set; }

    public virtual DbSet<Contest> Contest { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<CssVariables> CssVariables { get; set; }

    public virtual DbSet<CssVariables1> CssVariables1 { get; set; }

}

}

